enable_button: 9  # R1 shoulder button
enable_turbo_button: 10  # R2 shoulder button

axis_linear: 1
scale_linear: 0.7
scale_linear_turbo: 1.0 #1.5

axis_angular: 0
scale_angular: 0.4 
#scale_angular_turbo : 0.4 